require 'hoe'
require './lib/fifadat/convert/version.rb'

Hoe.spec 'fifadat-convert' do

  self.version = FifadatConvert::VERSION

  self.summary = "fifadat-convert - convert fifa api json"
  self.description = summary

  self.urls = { home: 'https://github.com/sportdb/sport.db' }

  self.author = 'Gerald Bauer'
  self.email  = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['fifadat'],
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
   required_ruby_version: '>= 3.1.0'
  }

end
